/* ***************************************************************************

Copyright (c): 2013 Hericus Software, Inc.

License: The MIT License (MIT)

Authors: Steven M. Cherry

*************************************************************************** */

#include <twine.h>
#include <Log.h>
#include <EnEx.h>
#include <dptr.h>
#include <Timer.h>
#include <HttpClient.h>
using namespace SLib;

#include "HelixApi.h"
using namespace Helix::Client;

/* ***************************************************************************** */
/* The implementation of HelixApi is broken up into 2 .cpp files.  This one is   */
/* auto-generated during the compile.                                            */
/* DO NOT EDIT THIS FILE.                                                        */
/* Edits to this file will be overwritten during the next compile.               */
/* ***************************************************************************** */

