var hierarchy =
[
    [ "Helix::Glob::ActionClass", "classHelix_1_1Glob_1_1ActionClass.html", [
      [ "Helix::Glob::ActionHtml", "classHelix_1_1Glob_1_1ActionHtml.html", null ],
      [ "Helix::Glob::ActionLogic", "classHelix_1_1Glob_1_1ActionLogic.html", null ],
      [ "Helix::Logic::admin::DeleteScheduleItem", "classHelix_1_1Logic_1_1admin_1_1DeleteScheduleItem.html", null ],
      [ "Helix::Logic::admin::DeleteSQLWork", "classHelix_1_1Logic_1_1admin_1_1DeleteSQLWork.html", null ],
      [ "Helix::Logic::admin::GetIAFileDetails", "classHelix_1_1Logic_1_1admin_1_1GetIAFileDetails.html", null ],
      [ "Helix::Logic::admin::GetIAFileList", "classHelix_1_1Logic_1_1admin_1_1GetIAFileList.html", null ],
      [ "Helix::Logic::admin::GetOneScheduleItem", "classHelix_1_1Logic_1_1admin_1_1GetOneScheduleItem.html", null ],
      [ "Helix::Logic::admin::GetScheduleItems", "classHelix_1_1Logic_1_1admin_1_1GetScheduleItems.html", null ],
      [ "Helix::Logic::admin::GetSQLTest", "classHelix_1_1Logic_1_1admin_1_1GetSQLTest.html", null ],
      [ "Helix::Logic::admin::GetSQLWork", "classHelix_1_1Logic_1_1admin_1_1GetSQLWork.html", null ],
      [ "Helix::Logic::admin::GetWorkFileList", "classHelix_1_1Logic_1_1admin_1_1GetWorkFileList.html", null ],
      [ "Helix::Logic::admin::LoadSQLTestMeta", "classHelix_1_1Logic_1_1admin_1_1LoadSQLTestMeta.html", null ],
      [ "Helix::Logic::admin::SaveIAFile", "classHelix_1_1Logic_1_1admin_1_1SaveIAFile.html", null ],
      [ "Helix::Logic::admin::SaveSQLTest", "classHelix_1_1Logic_1_1admin_1_1SaveSQLTest.html", null ],
      [ "Helix::Logic::admin::SaveSQLWork", "classHelix_1_1Logic_1_1admin_1_1SaveSQLWork.html", null ],
      [ "Helix::Logic::admin::UpdateScheduleItem", "classHelix_1_1Logic_1_1admin_1_1UpdateScheduleItem.html", null ],
      [ "Helix::Logic::dev::GetProject", "classHelix_1_1Logic_1_1dev_1_1GetProject.html", null ],
      [ "Helix::Logic::dev::GetProjectList", "classHelix_1_1Logic_1_1dev_1_1GetProjectList.html", null ],
      [ "Helix::Logic::dev::SaveProject", "classHelix_1_1Logic_1_1dev_1_1SaveProject.html", null ],
      [ "Helix::Logic::util::CleanoutLRTask", "classHelix_1_1Logic_1_1util_1_1CleanoutLRTask.html", null ],
      [ "Helix::Logic::util::CloseConnection", "classHelix_1_1Logic_1_1util_1_1CloseConnection.html", null ],
      [ "Helix::Logic::util::ConnectToServer", "classHelix_1_1Logic_1_1util_1_1ConnectToServer.html", null ],
      [ "Helix::Logic::util::ExecuteGenericSQL", "classHelix_1_1Logic_1_1util_1_1ExecuteGenericSQL.html", null ],
      [ "Helix::Logic::util::FindLogMessage", "classHelix_1_1Logic_1_1util_1_1FindLogMessage.html", null ],
      [ "Helix::Logic::util::GetAllLayouts", "classHelix_1_1Logic_1_1util_1_1GetAllLayouts.html", null ],
      [ "Helix::Logic::util::GetAllLRTasks", "classHelix_1_1Logic_1_1util_1_1GetAllLRTasks.html", null ],
      [ "Helix::Logic::util::GetHitMap", "classHelix_1_1Logic_1_1util_1_1GetHitMap.html", null ],
      [ "Helix::Logic::util::GetLogFiles", "classHelix_1_1Logic_1_1util_1_1GetLogFiles.html", null ],
      [ "Helix::Logic::util::GetLogMessages", "classHelix_1_1Logic_1_1util_1_1GetLogMessages.html", null ],
      [ "Helix::Logic::util::GetLogMessagesByRange", "classHelix_1_1Logic_1_1util_1_1GetLogMessagesByRange.html", null ],
      [ "Helix::Logic::util::GetLogMsgCount", "classHelix_1_1Logic_1_1util_1_1GetLogMsgCount.html", null ],
      [ "Helix::Logic::util::GetLogSettings", "classHelix_1_1Logic_1_1util_1_1GetLogSettings.html", null ],
      [ "Helix::Logic::util::GetOneLRTask", "classHelix_1_1Logic_1_1util_1_1GetOneLRTask.html", null ],
      [ "Helix::Logic::util::GetProfile", "classHelix_1_1Logic_1_1util_1_1GetProfile.html", null ],
      [ "Helix::Logic::util::SaveLayout", "classHelix_1_1Logic_1_1util_1_1SaveLayout.html", null ],
      [ "Helix::Logic::util::SaveLogMsg", "classHelix_1_1Logic_1_1util_1_1SaveLogMsg.html", null ],
      [ "Helix::Logic::util::SwitchServerConnection", "classHelix_1_1Logic_1_1util_1_1SwitchServerConnection.html", null ],
      [ "Helix::Logic::util::SystemProperties", "classHelix_1_1Logic_1_1util_1_1SystemProperties.html", null ],
      [ "Helix::Logic::util::UpdateLogSettings", "classHelix_1_1Logic_1_1util_1_1UpdateLogSettings.html", null ],
      [ "Helix::Logic::util::UserProperties", "classHelix_1_1Logic_1_1util_1_1UserProperties.html", null ]
    ] ],
    [ "Helix::Glob::ActionClassFactory", "classHelix_1_1Glob_1_1ActionClassFactory.html", [
      [ "Helix::Glob::ActionClassRegister< Helix::Glob::ActionHtml >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Glob::ActionLogic >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::DeleteScheduleItem >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::DeleteSQLWork >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetIAFileDetails >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetIAFileList >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetOneScheduleItem >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetScheduleItems >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetSQLTest >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetSQLWork >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::GetWorkFileList >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::LoadSQLTestMeta >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::SaveIAFile >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::SaveSQLTest >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::SaveSQLWork >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::admin::UpdateScheduleItem >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::dev::GetProject >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::dev::GetProjectList >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::dev::SaveProject >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::CleanoutLRTask >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::CloseConnection >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::ConnectToServer >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::ExecuteGenericSQL >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::FindLogMessage >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetAllLayouts >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetAllLRTasks >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetHitMap >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetLogFiles >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetLogMessages >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetLogMessagesByRange >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetLogMsgCount >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetLogSettings >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetOneLRTask >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::GetProfile >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::SaveLayout >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::SaveLogMsg >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::SwitchServerConnection >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::SystemProperties >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::UpdateLogSettings >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< Helix::Logic::util::UserProperties >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ],
      [ "Helix::Glob::ActionClassRegister< T >", "classHelix_1_1Glob_1_1ActionClassRegister.html", null ]
    ] ],
    [ "Helix::Glob::ActionMap", "classHelix_1_1Glob_1_1ActionMap.html", null ],
    [ "Helix::Glob::AdaptiveLogParm", "classHelix_1_1Glob_1_1AdaptiveLogParm.html", null ],
    [ "ah", "structah.html", null ],
    [ "Helix::Logic::dev::Api", "classHelix_1_1Logic_1_1dev_1_1Api.html", null ],
    [ "Helix::Logic::dev::Application", "classHelix_1_1Logic_1_1dev_1_1Application.html", null ],
    [ "cgi_env_block", "structcgi__env__block.html", null ],
    [ "Helix::Logic::admin::Col", "classHelix_1_1Logic_1_1admin_1_1Col.html", null ],
    [ "Helix::Glob::ColumnInfo", "classHelix_1_1Glob_1_1ColumnInfo.html", null ],
    [ "Helix::Glob::Connection", "classHelix_1_1Glob_1_1Connection.html", null ],
    [ "Helix::Glob::ConnectionPool", "classHelix_1_1Glob_1_1ConnectionPool.html", null ],
    [ "Helix::Glob::CPEntry", "classHelix_1_1Glob_1_1CPEntry.html", null ],
    [ "Helix::Glob::DataObjectTestClass", "classHelix_1_1Glob_1_1DataObjectTestClass.html", [
      [ "Helix::Logic::admin::ColTest", "classHelix_1_1Logic_1_1admin_1_1ColTest.html", null ],
      [ "Helix::Logic::admin::IAFileTest", "classHelix_1_1Logic_1_1admin_1_1IAFileTest.html", null ],
      [ "Helix::Logic::admin::IAFolderTest", "classHelix_1_1Logic_1_1admin_1_1IAFolderTest.html", null ],
      [ "Helix::Logic::admin::RowTest", "classHelix_1_1Logic_1_1admin_1_1RowTest.html", null ],
      [ "Helix::Logic::admin::SchedItemTest", "classHelix_1_1Logic_1_1admin_1_1SchedItemTest.html", null ],
      [ "Helix::Logic::admin::SQLStmtTest", "classHelix_1_1Logic_1_1admin_1_1SQLStmtTest.html", null ],
      [ "Helix::Logic::admin::SQLTestsTest", "classHelix_1_1Logic_1_1admin_1_1SQLTestsTest.html", null ],
      [ "Helix::Logic::admin::SQLWorkTest", "classHelix_1_1Logic_1_1admin_1_1SQLWorkTest.html", null ],
      [ "Helix::Logic::dev::ApiTest", "classHelix_1_1Logic_1_1dev_1_1ApiTest.html", null ],
      [ "Helix::Logic::dev::ApplicationTest", "classHelix_1_1Logic_1_1dev_1_1ApplicationTest.html", null ],
      [ "Helix::Logic::dev::DObjectTest", "classHelix_1_1Logic_1_1dev_1_1DObjectTest.html", null ],
      [ "Helix::Logic::dev::DOChildTest", "classHelix_1_1Logic_1_1dev_1_1DOChildTest.html", null ],
      [ "Helix::Logic::dev::DOStmtInputTest", "classHelix_1_1Logic_1_1dev_1_1DOStmtInputTest.html", null ],
      [ "Helix::Logic::dev::DOStmtOutputTest", "classHelix_1_1Logic_1_1dev_1_1DOStmtOutputTest.html", null ],
      [ "Helix::Logic::dev::DOStmtTest", "classHelix_1_1Logic_1_1dev_1_1DOStmtTest.html", null ],
      [ "Helix::Logic::dev::ProjectDataTest", "classHelix_1_1Logic_1_1dev_1_1ProjectDataTest.html", null ],
      [ "Helix::Logic::dev::ProjectTableTest", "classHelix_1_1Logic_1_1dev_1_1ProjectTableTest.html", null ],
      [ "Helix::Logic::dev::ProjectTest", "classHelix_1_1Logic_1_1dev_1_1ProjectTest.html", null ],
      [ "Helix::Logic::dev::ScreenTest", "classHelix_1_1Logic_1_1dev_1_1ScreenTest.html", null ],
      [ "Helix::Logic::dev::TableColTest", "classHelix_1_1Logic_1_1dev_1_1TableColTest.html", null ],
      [ "Helix::Logic::util::HitMapTest", "classHelix_1_1Logic_1_1util_1_1HitMapTest.html", null ],
      [ "Helix::Logic::util::LogMessageFilterTest", "classHelix_1_1Logic_1_1util_1_1LogMessageFilterTest.html", null ],
      [ "Helix::Logic::util::LogObjTest", "classHelix_1_1Logic_1_1util_1_1LogObjTest.html", null ],
      [ "Helix::Logic::util::LogOnTest", "classHelix_1_1Logic_1_1util_1_1LogOnTest.html", null ],
      [ "Helix::Logic::util::LogSettingsTest", "classHelix_1_1Logic_1_1util_1_1LogSettingsTest.html", null ],
      [ "Helix::Logic::util::LRTaskTest", "classHelix_1_1Logic_1_1util_1_1LRTaskTest.html", null ],
      [ "Helix::Logic::util::SchedItemTest", "classHelix_1_1Logic_1_1util_1_1SchedItemTest.html", null ],
      [ "Helix::Logic::util::SQLStatementTest", "classHelix_1_1Logic_1_1util_1_1SQLStatementTest.html", null ]
    ] ],
    [ "Helix::Glob::DataObjectTestClassFactory", "classHelix_1_1Glob_1_1DataObjectTestClassFactory.html", [
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::ColTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::IAFileTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::IAFolderTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::RowTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::SchedItemTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::SQLStmtTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::SQLTestsTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::admin::SQLWorkTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ApiTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ApplicationTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::DObjectTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::DOChildTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::DOStmtInputTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::DOStmtOutputTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::DOStmtTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ProjectDataTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ProjectTableTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ProjectTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::ScreenTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::dev::TableColTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::HitMapTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::LogMessageFilterTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::LogObjTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::LogOnTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::LogSettingsTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::LRTaskTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::SchedItemTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< Helix::Logic::util::SQLStatementTest >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ],
      [ "Helix::Glob::DataObjectTestClassRegister< T >", "classHelix_1_1Glob_1_1DataObjectTestClassRegister.html", null ]
    ] ],
    [ "Helix::Glob::DataObjectTestMap", "classHelix_1_1Glob_1_1DataObjectTestMap.html", null ],
    [ "de", "structde.html", null ],
    [ "Helix::Logic::dev::DObject", "classHelix_1_1Logic_1_1dev_1_1DObject.html", null ],
    [ "Helix::Logic::dev::DOChild", "classHelix_1_1Logic_1_1dev_1_1DOChild.html", null ],
    [ "Helix::Logic::dev::DOStmt", "classHelix_1_1Logic_1_1dev_1_1DOStmt.html", null ],
    [ "Helix::Logic::dev::DOStmtInput", "classHelix_1_1Logic_1_1dev_1_1DOStmtInput.html", null ],
    [ "Helix::Logic::dev::DOStmtOutput", "classHelix_1_1Logic_1_1dev_1_1DOStmtOutput.html", null ],
    [ "Helix::Logic::util::HitMap", "classHelix_1_1Logic_1_1util_1_1HitMap.html", null ],
    [ "HttpClient", null, [
      [ "Helix::Client::HelixApi", "classHelix_1_1Client_1_1HelixApi.html", null ]
    ] ],
    [ "Helix::Logic::admin::IAFile", "classHelix_1_1Logic_1_1admin_1_1IAFile.html", null ],
    [ "Helix::Logic::admin::IAFolder", "classHelix_1_1Logic_1_1admin_1_1IAFolder.html", null ],
    [ "Helix::Glob::IOAdapterFactory", "classHelix_1_1Glob_1_1IOAdapterFactory.html", [
      [ "Helix::Glob::IOAdapterRegister< T >", "classHelix_1_1Glob_1_1IOAdapterRegister.html", null ],
      [ "Helix::Glob::IOAdapterRegister< Helix::Glob::HttpIOAdapter >", "classHelix_1_1Glob_1_1IOAdapterRegister.html", null ]
    ] ],
    [ "Helix::Glob::IOConn", "classHelix_1_1Glob_1_1IOConn.html", [
      [ "Helix::Glob::HttpConn", "classHelix_1_1Glob_1_1HttpConn.html", null ],
      [ "Helix::Glob::SchedConn", "classHelix_1_1Glob_1_1SchedConn.html", null ]
    ] ],
    [ "Helix::Glob::Jvm", "classHelix_1_1Glob_1_1Jvm.html", null ],
    [ "Helix::Logic::util::LogMessageFilter", "classHelix_1_1Logic_1_1util_1_1LogMessageFilter.html", null ],
    [ "Helix::Logic::util::LogObj", "classHelix_1_1Logic_1_1util_1_1LogObj.html", null ],
    [ "Helix::Logic::util::LogOn", "classHelix_1_1Logic_1_1util_1_1LogOn.html", null ],
    [ "Helix::Logic::util::LogSettings", "classHelix_1_1Logic_1_1util_1_1LogSettings.html", null ],
    [ "Helix::Glob::LongRunningTask", "classHelix_1_1Glob_1_1LongRunningTask.html", null ],
    [ "Helix::Logic::util::LRTask", "classHelix_1_1Logic_1_1util_1_1LRTask.html", null ],
    [ "MD5Context", "structMD5Context.html", null ],
    [ "mg_connection", "structmg__connection.html", null ],
    [ "mg_context", "structmg__context.html", null ],
    [ "mg_request_info::mg_header", "structmg__request__info_1_1mg__header.html", null ],
    [ "mg_request_info", "structmg__request__info.html", null ],
    [ "mgstat", "structmgstat.html", null ],
    [ "Helix::Glob::OdbcDrv", "classHelix_1_1Glob_1_1OdbcDrv.html", null ],
    [ "Helix::Glob::OdbcObj", "classHelix_1_1Glob_1_1OdbcObj.html", null ],
    [ "Helix::Logic::dev::Project", "classHelix_1_1Logic_1_1dev_1_1Project.html", null ],
    [ "Helix::Logic::dev::ProjectData", "classHelix_1_1Logic_1_1dev_1_1ProjectData.html", null ],
    [ "Helix::Logic::dev::ProjectTable", "classHelix_1_1Logic_1_1dev_1_1ProjectTable.html", null ],
    [ "Helix::Logic::admin::Row", "classHelix_1_1Logic_1_1admin_1_1Row.html", null ],
    [ "Helix::Glob::SchedEntry", "classHelix_1_1Glob_1_1SchedEntry.html", null ],
    [ "Helix::Logic::admin::SchedItem", "classHelix_1_1Logic_1_1admin_1_1SchedItem.html", null ],
    [ "Helix::Logic::util::SchedItem", "classHelix_1_1Logic_1_1util_1_1SchedItem.html", null ],
    [ "Helix::Logic::dev::Screen", "classHelix_1_1Logic_1_1dev_1_1Screen.html", null ],
    [ "Helix::Glob::SessionInfo", "classHelix_1_1Glob_1_1SessionInfo.html", null ],
    [ "Helix::Glob::SessionList", "classHelix_1_1Glob_1_1SessionList.html", null ],
    [ "socket", "structsocket.html", null ],
    [ "Helix::Glob::SqlDB", "classHelix_1_1Glob_1_1SqlDB.html", null ],
    [ "Helix::Logic::util::SQLStatement", "classHelix_1_1Logic_1_1util_1_1SQLStatement.html", null ],
    [ "Helix::Logic::admin::SQLStmt", "classHelix_1_1Logic_1_1admin_1_1SQLStmt.html", null ],
    [ "Helix::Logic::admin::SQLTests", "classHelix_1_1Logic_1_1admin_1_1SQLTests.html", null ],
    [ "Helix::Logic::admin::SQLWork", "classHelix_1_1Logic_1_1admin_1_1SQLWork.html", null ],
    [ "ssl_func", "structssl__func.html", null ],
    [ "Helix::Logic::util::Statics", "classHelix_1_1Logic_1_1util_1_1Statics.html", null ],
    [ "Helix::Glob::TableActions", "classHelix_1_1Glob_1_1TableActions.html", null ],
    [ "Helix::Logic::dev::TableCol", "classHelix_1_1Logic_1_1dev_1_1TableCol.html", null ],
    [ "Helix::Glob::TheMain", "classHelix_1_1Glob_1_1TheMain.html", null ],
    [ "Helix::Glob::Threadable", "classHelix_1_1Glob_1_1Threadable.html", [
      [ "Helix::Glob::AdaptiveLogs", "classHelix_1_1Glob_1_1AdaptiveLogs.html", null ],
      [ "Helix::Glob::IOAdapter", "classHelix_1_1Glob_1_1IOAdapter.html", [
        [ "Helix::Glob::HttpIOAdapter", "classHelix_1_1Glob_1_1HttpIOAdapter.html", null ]
      ] ],
      [ "Helix::Glob::MsgProcessor", "classHelix_1_1Glob_1_1MsgProcessor.html", null ],
      [ "Helix::Glob::Scaler", "classHelix_1_1Glob_1_1Scaler.html", [
        [ "Helix::Glob::MsgProcScaler", "classHelix_1_1Glob_1_1MsgProcScaler.html", null ]
      ] ],
      [ "Helix::Glob::Schedule", "classHelix_1_1Glob_1_1Schedule.html", null ],
      [ "Helix::Glob::SessionSerializer", "classHelix_1_1Glob_1_1SessionSerializer.html", null ]
    ] ],
    [ "Helix::Glob::ThreadList", "classHelix_1_1Glob_1_1ThreadList.html", null ],
    [ "usa", "structusa.html", null ],
    [ "vec", "structvec.html", null ]
];